### ISSUE TITLE
Dataset does not exist? 

### ISSUE THREAD

**Issue by jscott5811** [AlekseyKorshuk/huggingartists#2]
Hi I'm trying to find a tutorial that explains this but I'm getting an error of  Couldn't find a dataset script. I'm getting stuck at the collect data section under preprocess data. I'm in colab on a free session.

**Comment by AlekseyKorshuk** [comment]
Hello. Can you share notebook with an error, so that I can reproduce it?

**Comment by jscott5811** [comment]
FileNotFoundError: Couldn't find a dataset script at
/content/huggingartists/owl-city/owl-city.py or any data file in the same
directory. Couldn't find 'huggingartists/owl-city' on the Hugging Face Hub
either: FileNotFoundError: Dataset 'huggingartists/owl-city' doesn't exist
on the Hub
Jesse Scott
***@***.***
